NIFTY50_STOCKS = [
    "ADANIENT.NS", "ADANIPORTS.NS", "APOLLOHOSP.NS", "ASIANPAINT.NS", "AXISBANK.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "BEL.NS", "BHARTIARTL.NS",
    "BPCL.NS", "BRITANNIA.NS", "CIPLA.NS", "COALINDIA.NS", "DRREDDY.NS",
    "EICHERMOT.NS", "ETERNAL.NS", "GRASIM.NS", "HCLTECH.NS", "HDFCBANK.NS",
    "HDFCLIFE.NS", "HEROMOTOCO.NS", "HINDALCO.NS", "HINDUNILVR.NS", "ICICIBANK.NS",
    "INDUSINDBK.NS", "INFY.NS", "ITC.NS", "JIOFIN.NS", "JSWSTEEL.NS",
    "KOTAKBANK.NS", "LT.NS", "M&M.NS", "MARUTI.NS", "NESTLEIND.NS",
    "NTPC.NS", "ONGC.NS", "POWERGRID.NS", "RELIANCE.NS", "SBILIFE.NS",
    "SBIN.NS", "SHRIRAMFIN.NS", "SUNPHARMA.NS", "TATACONSUM.NS", "TATASTEEL.NS",
    "TCS.NS", "TECHM.NS", "TRENT.NS", "ULTRACEMCO.NS", "WIPRO.NS",
]

TICKER_TO_ID = {ticker: idx for idx, ticker in enumerate(NIFTY50_STOCKS)}
DATA_START_DATE = "2012-01-01"

FEATURE_COLUMNS = [
    "Open", "High", "Low", "Close", "Volume",
    "return_1d", "ma_7", "ma_21", "volatility_7",
]

SEQUENCE_WINDOW_SIZE = 60
FORECAST_HORIZON_DAYS = 30

MODEL_TRAINER_EMBEDDING_DIM = 16
MODEL_TRAINER_CONV_FILTERS = 32
MODEL_TRAINER_LSTM_UNITS = 64
MODEL_TRAINER_DROPOUT = 0.3
MODEL_TRAINER_LEARNING_RATE = 0.0005
MODEL_TRAINER_BATCH_SIZE = 32
MODEL_TRAINER_EPOCHS = 50
MODEL_TRAINER_EARLY_STOPPING_PATIENCE = 10
MODEL_TRAINER_EXPECTED_MAE = 3.5

MODEL_EVALUATION_CHANGED_THRESHOLD_SCORE = 0.02
MODEL_BUCKET_NAME = "my-stock-mlopsproj"
MODEL_FILE_NAME = "model.keras"

AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
REGION_NAME = "us-east-1"

APP_HOST = "0.0.0.0"
APP_PORT = 5080